### ISSUE TITLE
Hot Water Control No Longer Available

### ISSUE THREAD

**Issue by Puntoboy** [asantaga/wiserHomeAssistantPlatform#114] opened 2020-07-18 05:02 UTC
I can't see to control the hot water any more. I can see the status of the hot water but can't turn it on or off.

Currently running 2.4beta1.

**Comment by asantaga** [comment] 2020-07-19 22:29
This is done by a service called `wiser.set_hotwater_mode`

takes one parameter, `hotwater_mode` which can be  on, off or auto

**Comment by Puntoboy** [comment] 2020-07-19 22:41
I’m not sure what I’m after, but I used to be able to have a card on Lovelace that allowed me to turn the hot water on or off. Now it won’t let me change it but will show me the current status.

**Comment by asantaga** [comment] 2020-07-19 22:55
Right,  I dont remember having this functionality, but I think I can put it in now..
Im looking at the code as we speak...

**Comment by Puntoboy** [comment] 2020-07-19 23:03
Weird. It definitely did. Now when I press the button on the card is throws an error.

**Comment by Puntoboy** [comment] 2020-07-19 23:05
Here the error.

**Comment by asantaga** [comment] 2020-07-19 23:06
its been a while .. However Ive just discovered a snag..  hotwater can be on, off or auto..... I need to work out how to cope with this...
otherwise implementation is straightforward , an entry in const.py and then a elif in switch.py

**Comment by asantaga** [comment] 2020-07-19 23:12
Silly question, how did u add the card? I didnt think sensors get added as cards.?

**Comment by asantaga** [comment] 2020-07-19 23:22
ok, 

Figured it out. You need to add three buttons (on/off/auto) using the Button component

e.g. 
1. Add a button using the UI Editor, map it to sensor_hot_water
2.  Go to code editor and add the following
`entity: sensor.wiser_hot_water
show_icon: true
show_name: true
tap_action:
  action: call-service
  service: wiser.set_hotwater_mode
  service_data:
    hotwater_mode: 'on'
type: button`

The above does the biz for **on** you will need two more for auto and off.. You can bundle them together using a horizontal stack

**Comment by Puntoboy** [comment] 2020-07-20 09:52
I'm not sure I did anything, I think it was added when the two room thermostats were added to lovelace. 

Here is the code for the card.

`entity: sensor.wiser_hot_water
hold_action:
  action: more-info
show_icon: true
show_name: true
tap_action:
  action: toggle
type: button`

**Comment by Puntoboy** [comment] 2020-10-06 10:11
Any update on this?

**Comment by asantaga** [comment] 2020-10-18 11:38
Sorry was otherwise distracted in the last month or so (covid, baby, work etc). 

Will look at this , later this week.

**Comment by msp1974** [comment] 2020-10-30 18:58
Reading the info on this I'm thinking the issue is that you have created a button entity for this sensor with an action of toggle.  By default this calls a turn on or turn off service which does not exist on this sensor.  Not sure whether this is something we have changed (I don't think so) or a change in Hassio.

However, to fix it, you need to do as Angelo has laid out above and create a button for each 'mode' (on/off/auto).

**Comment by msp1974** [comment] 2020-10-30 19:07
Sorry should have added, if you want to get a little more clever, then you can create a single button that calls a script.  This script can then call the service with the mode setting based on the current value.  Ie if it is already on, set it to auto/off.  If it is auto/on, set to off.

**Comment by Puntoboy** [comment] 2020-10-30 20:03
This was working perfectly fine. I didn’t do anything special. The entities were listed under the integration and I clicked add to Lovelace :)

Kind regards,
Chris Jeffrey

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by msp1974** [comment] 2020-10-30 20:58
Chris, that maybe but I think this is then a change in Hassio and not something the integration originally supported.  Does the solution proposed by Angelo not work for you?

**Comment by Puntoboy** [comment] 2020-11-02 10:39
> 
> 
> Chris, that maybe but I think this is then a change in Hassio and not something the integration originally supported. Does the solution proposed by Angelo not work for you?

This does work :) Not as elegant as it used to be but it works. No idea what changed to break it in the first place.

`show_icon: true
show_name: true
tap_action:
  action: call-service
  service: wiser.set_hotwater_mode
  service_data:
    hotwater_mode: 'on'
type: button
entity: sensor.wiser_hot_water
name: Hot water On`

**Comment by asantaga** [comment] 2020-11-21 17:54
Hey Puntoboy, can we close this then?

**Closed** 2020-11-21 18:37 UTC
