### ISSUE TITLE
Heads up: depreciation warning in Logs

### ISSUE THREAD

**Issue by andyblac** [asantaga/wiserHomeAssistantPlatform#465] opened 2024-04-06 14:51 UTC
just a heads error in logs
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: 12:41:00 (1 occurrences)
Last logged: 12:41:08

Detected that custom integration 'wiser' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/wiser/__init__.py, line 54: hass.async_add_job(, please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues
```

**Comment by msp1974** [comment] 2024-04-07 11:53
Thanks but duplicate of #463 . Will close this and track on initial one.

**Closed by msp1974** 2024-04-07 11:53 UTC
