### ISSUE TITLE
R3.0.17RC1 - Heating Actuators error

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#204] opened 2021-12-29 18:06 UTC
After a cleaning of the wiser heat hub (erase an actuator and reinstalled it in another room), the data weren't updated.
I try to reload the integration, to erase it and reinstall, I restart after restore an application from last week (before the tests) without no positive result.
extract of the log file

2021-12-29 18:54:09 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wiser platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wiser/sensor.py", line 49, in async_setup_entry
    WiserDeviceSignalSensor(data, device.id, device.product_type)
  File "/config/custom_components/wiser/sensor.py", line 240, in __init__
    super().__init__(data, device_id, sensor_type)
  File "/config/custom_components/wiser/sensor.py", line 130, in __init__
    _LOGGER.debug(f"{self._data.wiserhub.system.name} {self.name} initalise")
  File "/config/custom_components/wiser/sensor.py", line 256, in name
    return f"{get_device_name(self._data, self._device_id)} Signal"
  File "/config/custom_components/wiser/helpers.py", line 27, in get_device_name
    if device_room.number_of_heating_actuators > 1:
AttributeError: 'NoneType' object has no attribute 'number_of_heating_actuators'

Thanks

**Comment by msp1974** [comment] 2021-12-29 20:10
Can you send me your data/v2/domain output as need to understand more how you have this setup.

**Comment by LGO44** [comment] 2021-12-29 22:27
I’m sorry, but where can I find this file? is it home-assistant_v2.db or .db-shm or db-Wal?
My  level in Home assistant and linux are  under 0.

**Comment by LGO44** [comment] 2021-12-29 22:54
If I put in comment the lines 27 to 36 in helpers.py as in the screen shot 
![image](https://user-images.githubusercontent.com/95585425/147708976-286e8c6a-c40d-4243-ac11-272672ec64fe.png)

I get my quite all  my wiser devices except the heating actuators that are called Wiser "serial number"

**Comment by msp1974** [comment] 2021-12-30 00:23
> I’m sorry, but where can I find this file? is it home-assistant_v2.db or .db-shm or db-Wal?

This is the wireshark output you provided previously.

**Comment by msp1974** [comment] 2021-12-30 11:51
@LGO44 I think the issue is caused by you not having a room assigned to 1 (or more) of your devices.  I have updated the above code to make the device name the product type and product id if it is not assigned to a room.  If you then later assign it to a room, you will have an orphaned device which you will need to remove with the remove_orphaned_devices service (see documentation).

Let me know if this now works.
Mark

**Comment by LGO44** [comment] 2021-12-30 21:05
Sorry but I wasn't available today.
Here is a file got with wireshark of my wiser hub data.
[Traces Wireshark WISER HUB 2021 12 30.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7794597/Traces.Wireshark.WISER.HUB.2021.12.30.zip)

**Comment by LGO44** [comment] 2021-12-30 21:14
@msp1974  With the release 3.0.18 my system id OK
Thanks a lot for all your job and your availability
Christian

**Comment by msp1974** [comment] 2021-12-30 23:09
Great. I'll close this issue for now. Reach out if you have any more issues.Sent from my Galaxy

**Comment by LGO44** [comment] 2021-12-31 21:24
Happy new year to the community.
Best wishes for the wiser community


Envoyé de mon iPhone

**Closed** 2022-01-05 17:03 UTC
