### ISSUE TITLE
Error in the logs release 3.0.15

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#197] opened 2021-12-25 10:20 UTC
Hello the community,

I have an error in the log

_2021-12-25 10:36:54 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform wiser
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/wiser/sensor.py", line 303, in extra_state_attributes
    attrs["repeater"] = self._data.wiserhub.devices.get_by_node_id(device_data.parent_node_id).name
AttributeError: 'NoneType' object has no attribute 'name'_

Thanks
Christian

**Comment by LGO44** [comment] 2021-12-25 10:59
In my case, I have some zigbee shutters that work as repeater but they are not taken in account in the liste of list of devices.

**Comment by msp1974** [comment] 2021-12-25 11:14
Yes this will be caused by your zigbee shutters being used as repeaters and it is trying to get the name of the repeater, assuming it is a registered wiser device.

Will provide a fix for this in next couple of days.  Even us community coders get Xmas day off! 😀

In the meantime, if you want a workaround to this, just comment out line 303 in sensor.py for it to load them.

**Comment by LGO44** [comment] 2021-12-25 11:59
Thanks a lot, have a very merry christmas 
enjoy your time off

**Comment by msp1974** [comment] 2021-12-28 23:13
Closing as fixed in 3.0.16/17

**Closed by msp1974** 2021-12-28 23:13 UTC
