### ISSUE TITLE
Multiple warning messages with no TRV Valves

### ISSUE THREAD

**Issue by naylogj** [asantaga/wiserHomeAssistantPlatform#28] opened 2019-07-21 13:27 UTC
Runing HA 0.96.2 and the latest version of the master branch of the wiser custom component.

I am running the Smart Hub (with hot water control), I purchased 2 TRV Valves but have not yet taken them out of the box.  Every 5 mins the following messages are logged in the HA log.

2019-07-21 11:59:57 WARNING (SyncWorker_18) [custom_components.wiser.wiserAPI.wiserHub]  Room doesnt contain any smart valves, maybe an error/corruption?? 
2019-07-21 11:59:57 WARNING (SyncWorker_16) [custom_components.wiser.wiserAPI.wiserHub]  Room doesnt contain any smart valves, maybe an error/corruption??

**Comment by asantaga** [comment] 2019-07-22 11:14
Duplicate of  issue #10 I think, can u look and confirm. I've not fixed it so far as it doesnt really stop the thing from working, most/all people will have a TRV anyway and Ive been focusing on trying to package up the component as part of HA... 

All excuses I know :-(.... I'll fix it sooner than later :-)

Can u check issue#10 if its the same then we can close it as a dupe and I'll also rename #10

**Comment by djashjones** [comment] 2019-09-22 07:14
I can confirm the issue and I've got no TRV's on my rads. Will install them one day but can't face draining the system to change the valve bodies.

Awesome job thou.

**Comment by mrvladis** [comment] 2019-09-22 07:21
Why do you think you need to drain the system to install TRVs?
They should be easely changeable!

**Comment by djashjones** [comment] 2019-09-22 07:26
My Rad's don't have TRV's fitted at all.

**Comment by mrvladis** [comment] 2020-01-12 10:49
@asantaga Any plan to amend the logic to avoid this error?

**Comment by asantaga** [comment] 2020-01-12 12:00
@msp1974 just fixed this in the core api so the errors should no longer show.
Will release a new HA component today using HACS

**Closed by asantaga** 2020-01-12 12:00 UTC
