### ISSUE TITLE
Consumption of my energy sensors randomly goes to 0 and initiate a new cycle for my energy dashboard by mistake

### ISSUE THREAD

**Issue by tcavin** [asantaga/wiserHomeAssistantPlatform#471] opened 2024-04-26 15:57 UTC
Hi @msp1974,

For an easier following, I document here the problem I have with my energy sensors which return to 0 randomly and broke my energy dashboard filtered by device (Cf discussion in the blog here : https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/3625)

As you can see below, I have the consumption of my wiser heater energy sensors which randomly return to 0.  (Here the consumption of my bathroom heater)

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/3537404/40328f49-e24e-48dc-9380-22e03ed90930)

And the problem is that It detects a new cycle for my energy dashboard :

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/3537404/89df6ec0-681c-4e01-910e-bd994dd33a8f)

It can be seen below that a behavior has changed (around April. While consumption was continuously increasing before April) :

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/3537404/f9f2223e-0292-48ce-a7de-679b313a6d50)

Many Thanks for your help

**Comment by msp1974** [comment] 2024-05-04 14:38
I think this was caused by a change in HA.  I am reworking some of the inegration to hopefullyprevent this.  I think it happens when the update from the hub fails due to hub dropping off wifi.

There should be an updated version today or tomorrow to see if this resolves.

**Comment by msp1974** [comment] 2024-05-04 15:52
Should be resolved in v3.4.7.  Energy sensors will show unknown if not provided by hub.  Let me know.

**Comment by tcavin** [comment] 2024-05-06 07:42
Hi @msp1974 
Thanks for your work
It seems to be ok now with the v 3.4.7. Energy sensors are not set to 0 anymore, even if there is an hub unavailability :
![Image 06-05-2024 à 09 35](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/3537404/366cd1b7-88ef-4562-a313-4e117d4bd715)
👍

**Comment by senna1992** [comment] 2024-05-09 06:46
tipp for those of you who use nodered: 
i fetch the sensor from wiser there and filter it for unknown / 0 etc by using a switch node.
then the value is being sent to HA as a new sensor using a "sensor" node, which can be allocated to a virtual device nodered creates. 


Never had issues alike since

**Comment by msp1974** [comment] 2024-05-11 19:21
Closing as resolved.

**Closed by msp1974** 2024-05-11 19:21 UTC
Labels: bug
