### ISSUE TITLE
Trouble with the new boost function

### ISSUE THREAD

**Issue by sparkymck** [asantaga/wiserHomeAssistantPlatform#40] opened 2020-01-05 16:53 UTC
I love this Add-on, it is probably the thing that made me buy the Wiser system in the first place.

I love the new inclusion of boost but I can't get it to work. I get the following error:

`Log Details (ERROR)
Sun Jan 05 2020 16:34:04 GMT+0000 (Greenwich Mean Time)
Error setting mode to error boost 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 421, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/climate.py", line 200, in set_preset_mode
    self.handler.set_room_mode(self.roomId, preset_mode, boost_temp, boost_time)
  File "/config/custom_components/wiser/__init__.py", line 157, in set_room_mode
    boost_time)
  File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 328, in setRoomMode
    raise Exception("Error setting mode to error {} ".format(mode))
Exception: Error setting mode to error boost `

And

`Log Details (ERROR)
Sun Jan 05 2020 16:48:31 GMT+0000 (Greenwich Mean Time)
Set Room mode to boost resulted in 400`

Thanks for any help you can offer, and keep up the awesome work!

**Comment by sparkymck** [comment] 2020-01-05 16:56
Forgot to add, I've got 1.7.1 running on a Pi3 with Hassio 103.4.

**Comment by asantaga** [comment] 2020-01-06 09:47
mmmm something it doesnt like at the REST API place.. im sure  i tested this too...

Alas my server (my whole HA installation ) is down and I dont have the time to rebuild it yet (got to do a complex tax return first....)

**Comment by asantaga** [comment] 2020-01-06 09:49
@msp1974 Hey Mark, given my server is down and time poor, any chance you have time to look at this?
Happy to accept any PR and merge as always

**Comment by asantaga** [comment] 2020-01-08 15:29
server back up :-) will work on this asap

**Comment by sparkymck** [comment] 2020-01-08 19:34
Awesome, thank you!

**Comment by msp1974** [comment] 2020-01-09 00:02
Sorry for late response i have been away. I can look at the weekend if you need some help. I found that the error message in the api could do with enhancimg to log the return response better so we can diagnose issues more easily.

**Comment by msp1974** [comment] 2020-01-09 00:12
The one thing i can think off that may cause an error that is not being checked is your boost_temp setting. The boost function takes the current temp of the room  and adds the boost_temp value to it.  This was a breaking change from prior version.

If you still have boost_temp set to something like 20 and not something like 2, current temp + boost temp will be more than 30 which is the max temp setting of the wiser system and it will error when setting boost mode.

There is no checking for the min/max temp range when setting the boost in the api like we have when setting a temp value. Maybe we need to add this and return a message to explain the issue.

**Comment by msp1974** [comment] 2020-01-09 00:40
Other possibility is it is being caused by the open issue 3 on the api that it does not always send an integer to wiser but sends a float value.

**Comment by sparkymck** [comment] 2020-01-09 07:23
> The one thing i can think off that may cause an error that is not being checked is your boost_temp setting. The boost function takes the current temp of the 
> If you still have boost_temp set to something like 20 and not something like 2, current temp + boost temp will be more than 30 which is the max temp setting of the wiser system and it will error when setting boost mode.

Thanks Mark, where would I find boost_temp? I definitely haven't deliberately changed anything from the defaults.

**Comment by msp1974** [comment] 2020-01-09 11:54
It will be in your configuration.yaml file where you have your settings for IP, secretkey etc.

**Comment by sparkymck** [comment] 2020-01-09 18:32
I'm a muppet, boost temp was indeed set to 20. Sorry for the trouble and thank you both for your help.

**Comment by asantaga** [comment] 2020-01-10 09:50
ReOpening this, Server is back but work and kids are also demanding. I plan to make some changes this weekend , merge a PR and what I'll do is add some checks for boost values > 10..

**Comment by msp1974** [comment] 2020-01-11 18:19
Have sent you a PR on the wiserHubAPI to fix this.

KR

**Comment by asantaga** [comment] 2020-01-11 18:47
Thanks.. really appreciate this

Ill.merge into master tonight/ tomorrow morning and make a new HCAS release.

**Comment by asantaga** [comment] 2020-01-12 11:58
thank you, closing this and creating a new HACS release

**Closed by asantaga** 2020-01-12 11:58 UTC
