### ISSUE TITLE
Error requesting wiser (wiser-WiserHeat<removed>) data: Response payload is not completed

### ISSUE THREAD

**Issue by Jonesnetwork** [asantaga/wiserHomeAssistantPlatform#341] opened 2023-01-18 11:56 UTC
Error showing in HA log as per the below:

ERROR:

Logger: custom_components.wiser.coordinator
Source: helpers/update_coordinator.py:168
Integration: Drayton Wiser Integration for Home Assistant ([documentation](https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/README.md), [issues](https://github.com/asantaga/wiserHomeAssistantPlatform/issues))
First occurred: 11:10:30 (1 occurrences)
Last logged: 11:10:30

Error requesting wiser (wiser-WiserHeat<removed>) data: Response payload is not completed

**Comment by msp1974** [comment] 2023-01-18 18:40
I am seeing this when the hub drops the wifi.  Did that happen at the time of this error?

**Comment by nottledim** [comment] 2023-01-20 14:30
I've had a lot of bother with this.  It seems to be related to wifi signal.  I resolved this problem by installing an access point close to the wiser hub. It seems to need a very loud wifi signal for it to be reliable.

**Comment by Jonesnetwork** [comment] 2023-01-20 14:33
Its certainly not a wifi issue from my side (Again AP is only a few meters away) - plus i've replaced the previous wifi incase it was an issue.

I have read posts where alot of people appear to be having issues where the hub drops the connection, which is apparently related to firmware (and the community is waiting for the firmware update to be released) - im just waiting support to confirm this so i can publish there response.

**Comment by nottledim** [comment] 2023-01-20 14:56
I suspect you're right.  There is something quite flaky in the hub's wifi.  I look forward to a resolution.  Meanwhile many expletives deleted. :-)

My hub is running version 3.10.8  I have no idea if that is the latest version or not.  Wiser are very coy about version numbers they just say hub will update automatically.

**Comment by msp1974** [comment] 2023-02-06 12:02
Closing this issue as a duplicate of #307

**Closed by msp1974** 2023-02-06 12:02 UTC
