### ISSUE TITLE
Roomstat battery levels seem wrong

### ISSUE THREAD

**Issue by phixion** [asantaga/wiserHomeAssistantPlatform#90] opened 2020-04-03 02:38 UTC
2.x -> 30%
![2](https://i.phx.ms/3D1L.png)

1.9: -> 77% (this value seems correct as its this value in the app and on the thing itself aswell)
![1.9](https://i.phx.ms/K1DM.png)

the iTRVs seem fine, which is weird since its the same formula that is used

**Comment by asantaga** [comment] 2020-04-03 08:34
Is this using 2.1 or the beta release i did last night (2.2alpha)

**Comment by asantaga** [comment] 2020-04-03 08:41
Im seeing this now, actually I think this is a bug in the itrv (which I added last night).. The battery % is wrong, I forgot to take into account the "base" voltage..

Can u confirm?

**Comment by asantaga** [comment] 2020-04-03 08:54
I've pushed a fix (which makes the values the same) in master. 

I can creatre a new release (R2.2alpha2) but an easier way to test is to just patch the sensor file..

Easiest way is 

```
https://raw.githubusercontent.com/asantaga/wiserHomeAssistantPlatform/master/custom_components/wiser/sensor.py
```

Now back to work, got loads to do today :-(

**Comment by msp1974** [comment] 2020-04-03 12:42
Just a comment from me that was outstanding from the v2.0 release as to whether the BATTERY_MIN value is set correctly in const.py.  I think it maybe set too low to be correctly identifying low battery level in the TRVs and when they need replacing.  @asantaga this was based on your conversations previously with Wiser.

We may want to make a decision on what the min should be on this basis.

**Comment by phixion** [comment] 2020-04-05 04:05
Using sensor.py from https://github.com/asantaga/wiserHomeAssistantPlatform/commit/5ebca8bd0f93a769d81fd69144a626f128391821#diff-0ff60fdf1d7d6163cfccdfbfd01a6660 had no effect :(

**Comment by asantaga** [comment] 2020-04-05 23:40
I was looking at this and for all of my devices i see :
```
voltage     Wiser Reports
26             LOW
27             OneThird
28             TwoThirds
29             Normal
```

I didnt have any more than 2.9 ( in theory two x 1.5 batteries are going to be 30 or maybe 31 
 3.0v/3.1v give or take) but then they'll very quickly they'll drop to 29 (2.9v)

I'm thinking if we use 25 as the MIN and 30 as the max then the figures look like this, and corresponding WISER text

```
voltage     Wiser Reports     We Report 
26             LOW                     20%
27             OneThird             40%
28             TwoThirds            60%
29             Normal                80%
```

The issue is that at 26 the batteries are probably not "Dead" but pretty much dead for Wiser

Seeing https://trueadolescents.com/aa-battery-voltage-range/ , apparently 1.5v cells are considered dead at 1.2v (ie 2.4v for 2) so 25 is probably a good value ( i tried 24 and the results dont match what wiser think)..


Go with 25 as Min and 30 as Max?

**Comment by msp1974** [comment] 2020-04-06 08:29
I think that sounds good.  When previously playing, I was ending up with weird % values but doing in 20's I think looks good.  I think I have seen 31 but agreed it wouldn't last long at this level and so long as we ensure that anything over 30 shows as 100% I think that will work well.

**Comment by asantaga** [comment] 2020-04-06 08:48
I'll modify the constants now and also modify the code so we dont report % more than 100 :-) , just in case!

**Comment by asantaga** [comment] 2020-04-06 21:40
Initial commit done in https://github.com/asantaga/wiserHomeAssistantPlatform/commit/896723cb58b6c9d3e5f1fb6e7fb379c06712218e and Im happy with TRV values matching (roughly) what wiser reports in text.. 

BUT the values dont ring true for roomstats..

itrvs are considered dead at 25 but roomstats go much lower..


Currently my room stat is at voltage 25 (2.5v) and wiser reports them as "NORMAL", need a few more measurements to work out what low is for a roomstat..

![image](https://user-images.githubusercontent.com/2940224/78607758-99708f00-7857-11ea-9646-4c742aaebb66.png)

**Comment by scooper1** [comment] 2020-04-06 22:24
roomstat is 2.9v normal

**Comment by Fulch** [comment] 2020-04-06 23:02
Roomstat.
battery_voltage: 29
battery_percent: 80
battery_level: Normal

**Comment by msp1974** [comment] 2020-04-06 23:09
Mines also 29 and Normal. Not much variation to help you, sorry

**Comment by phixion** [comment] 2020-04-08 08:46
thanks for everyones effort

**Comment by asantaga** [comment] 2020-04-08 20:46
mmm so 29 is Normal and 24 TwoThirds... we'd need one more measurement to understand the range..

I think Im gonna have to find some old batteries from my son's toys

**Comment by phixion** [comment] 2020-04-09 20:36
good call, let me find shitty batteries and throw them in

**Comment by msp1974** [comment] 2020-04-10 19:43
I have a variable voltage supply arriving tomorrow so will connect to roomstat and a trv, do tests on the whole range and report back the status from the hub.

**Comment by msp1974** [comment] 2020-04-11 20:08
Ok. Have done testing on Roomstat and results are below:

2.5v+ - Normal
2.2v,2.3v,2.4v - 2/3
1.9v, 2.0v, 2.1v - 1/3
1.8v - Low
Below 1.8v no longer operates.
So think our range should by min 1.7 to max - 2.7 to gives us a 10% change for each volt below 2.7.  Anything above can show 100%.  This way 10% is our low value but I guess it will never go to zero as roomstat will stop working before it send update.

Will do same testing on a iTRV to make sure we are consistent.

**Comment by msp1974** [comment] 2020-04-11 20:17
iTRV is as below
2.9v+ - Norma;
2.8v - 2/3
2.7v - 1/3
2.6v - Low

**Comment by asantaga** [comment] 2020-04-12 14:17
cool, I actually found a few batteries and yeah about the same results ( i only tested the room stat)

I'll implement this tonight.

I'll leave TRVs as they are , and do roomstats 1.7 to 2.7 as the range..

**Comment by asantaga** [comment] 2020-04-12 22:27
this is done, please test in from the dev branch. , however to me looks right.

I'll merge into master tomorrow and make a 2.2 release if all good

**Closed by asantaga** 2020-04-12 22:27 UTC
