### ISSUE TITLE
potential typo on line 198 of wiserHub.py

### ISSUE THREAD

**Issue by jameslillystone** [asantaga/wiserHomeAssistantPlatform#20] opened 2019-04-17 16:39 UTC
Firstly massive thank you for writing this addon :-)

In your readme there is an example yaml config with the following:

```
wiser:
  host: 
  password: 
  scan_interval: 300
  minimum: -5
  boost_temp: 24
  boost_time: 30
```

Using this example I get the following error within Home Assistant:

> Configuration invalid
> Invalid config for [wiser]: [boost_time] is an invalid option for [wiser]. Check: wiser->boost_time. (See /config/configuration.yaml, line 48). Please check the docs at https://home-assistant.io/components/wiser/

I beliew that either you have a typo on line 189 of wiserHub.py and `boost_time_temp` should read `boost_time` or you have a typo in the readme doc and `boost_time` should read `boost_temp_time`
```
#Set Room Mode (Manual, Boost or Auto)
    def setRoomMode(self,roomId, mode,boost_temp=20,boost_temp_time=30):
        # TODO
        _LOGGER.debug("Set Mode {} for a room {} ".format(mode,roomId))
        if (mode.lower()=="auto"):
```

**Comment by asantaga** [comment] 2019-04-17 17:08
ooops, will double check my installation at home and correct.. :-)

**Comment by asantaga** [comment] 2019-04-20 20:26
This should fix it, works for me please test, if all good then we can close this one off :-)

**Comment by asantaga** [comment] 2019-04-25 08:45
confirmed fixed

**Closed by asantaga** 2019-04-25 08:45 UTC
